

specs = [
    'auto', 'AUTO',
    'break', 'BREAK',
    'case', 'CASE',
    'char', 'CHAR',
    'const', 'CONST',
    'continue', 'CONTINUE',
    'default', 'DEFAULT',
    'do', 'DO',
    'double', 'DOUBLE',
    'else', 'ELSE',
    'enum', 'ENUM',
    'extern', 'EXTERN',
    'float', 'FLOAT',
    'for', 'FOR',
    'goto', 'GOTO',
    'if', 'IF',
    'int', 'INT',
    'long', 'LONG',
    'register', 'REGISTER',
    'return', 'RETURN',
    'short', 'SHORT',
    'signed', 'SIGNED',
    'sizeof', 'SIZEOF',
    'static', 'STATIC',
    'struct', 'STRUCT',
    'switch', 'SWITCH',
    'typedef', 'TYPEDEF',
    'union', 'UNION',
    'unsigned', 'UNSIGNED',
    'void', 'VOID',
    'volatile', 'VOLATILE',
    'while', 'WHILE',

    "&", "&",
    ";", ";",
    '{', "{",
    '}', "}",
    ",", ",",
    ",", "",
    "=", "=",
    "(", "(",
    ")", ")",
    "[", "[",
    "]", "]",
    ".", ".",

    "!", "!",
    "~", "~",
    "-", "-",
    "+", "+",
    "*", "*",
    "/", "/",
    "%", "%",
    "<", "<",
    ">", ">",
    "^", "^",
    "|", "|",
    "?", "?",

    ">>=", ">>=",
    "<<=", "<<=",
    "+=", "+=",
    "-=", "-=",
    "*=", "*=",
    "/=", "/=",
    "%=", "%=",
    "&=", "&=",
    "^=", "^=",
    "|=", "|=",
    ">>", ">>",
    "<<", "<<",
    "++", "++",
    "--", "--",
    "->", "->",
    "&&", "&&",
    "||", "||",
    "<=", "<=",
    ">=", ">=",
    "==", "==",
    "!=", "!=",



    " ", "WHITESPACE",
    "\t", "WHITESPACE",
    "\v", "WHITESPACE",
    "\n", "WHITESPACE",
    "\f", "WHITESPACE",
    "\r", "WHITESPACE",

]

